name = "black-lily-elite"
main = "src/index.js"
compatibility_date = "2024-03-16"

[[d1_databases]]
binding = "DB"
database_id = "c6e1cb30-0fdf-4563-b1fe-6e48a37a9a2b"
database_name = "baxto-db"

[[kv_namespaces]]
binding = "SESSIONS"
id = "a136dcf8ea7f4d428a836f6763bb112f"


[triggers]
crons = ["*/15 * * * *"]
